### ISSUE TITLE
Add the ability to tweak or disable rules

### ISSUE THREAD

**Issue by MOZGIII** [mmozuras/poper#2]
We use different rules. An easy way tweak or disable existing ones would be great.

**Comment by supremebeing7** [comment]
If @mmozuras agrees this would be beneficial, and if @MOZGIII hasn't started on this, I can try to code something for it in the coming weeks.

**Comment by mmozuras** [comment]
@supremebeing7 go ahead, that would be great! You can look at how [Pronto](https://github.com/mmozuras/pronto) does configuration, if you want something to copy 😄
